version: '3'
services:
  # celery, ..., ...
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_usr
      - POSTGRES_PASSWORD=Qwerty12345!
    ports:
      - "5433:5433"
    expose:
      - 5433
  cache:
    image: "redis:latest"
    ports:
      - "6381:6381"
    expose:
      - 6381
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
      - cache
